/*
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BreRuleLog :  IEquatable<BreRuleLog>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BreRuleLog" /> class.
        /// </summary>
        /// <param name="Ran">Whether the rule ran.</param>
        /// <param name="Reason">The reason for the rule.</param>
        /// <param name="RuleEndDate">The end date of the rule in seconds.</param>
        /// <param name="RuleId">The id of the rule.</param>
        /// <param name="RuleName">The name of the rule.</param>
        /// <param name="RuleStartDate">The start date of the rule in seconds.</param>
        public BreRuleLog(bool? Ran = null, string Reason = null, long? RuleEndDate = null, string RuleId = null, string RuleName = null, long? RuleStartDate = null)
        {
            this.Ran = Ran;
            this.Reason = Reason;
            this.RuleEndDate = RuleEndDate;
            this.RuleId = RuleId;
            this.RuleName = RuleName;
            this.RuleStartDate = RuleStartDate;
            
        }

        /// <summary>
        /// Whether the rule ran
        /// </summary>
        /// <value>Whether the rule ran</value>
        [DataMember(Name="ran")]
        public bool? Ran { get; set; }

        /// <summary>
        /// The reason for the rule
        /// </summary>
        /// <value>The reason for the rule</value>
        [DataMember(Name="reason")]
        public string Reason { get; set; }

        /// <summary>
        /// The end date of the rule in seconds
        /// </summary>
        /// <value>The end date of the rule in seconds</value>
        [DataMember(Name="rule_end_date")]
        public long? RuleEndDate { get; set; }

        /// <summary>
        /// The id of the rule
        /// </summary>
        /// <value>The id of the rule</value>
        [DataMember(Name="rule_id")]
        public string RuleId { get; set; }

        /// <summary>
        /// The name of the rule
        /// </summary>
        /// <value>The name of the rule</value>
        [DataMember(Name="rule_name")]
        public string RuleName { get; set; }

        /// <summary>
        /// The start date of the rule in seconds
        /// </summary>
        /// <value>The start date of the rule in seconds</value>
        [DataMember(Name="rule_start_date")]
        public long? RuleStartDate { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BreRuleLog {\n");
            sb.Append("  Ran: ").Append(Ran).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  RuleEndDate: ").Append(RuleEndDate).Append("\n");
            sb.Append("  RuleId: ").Append(RuleId).Append("\n");
            sb.Append("  RuleName: ").Append(RuleName).Append("\n");
            sb.Append("  RuleStartDate: ").Append(RuleStartDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((BreRuleLog)obj);
        }

        /// <summary>
        /// Returns true if BreRuleLog instances are equal
        /// </summary>
        /// <param name="other">Instance of BreRuleLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BreRuleLog other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Ran == other.Ran ||
                    this.Ran != null &&
                    this.Ran.Equals(other.Ran)
                ) && 
                (
                    this.Reason == other.Reason ||
                    this.Reason != null &&
                    this.Reason.Equals(other.Reason)
                ) && 
                (
                    this.RuleEndDate == other.RuleEndDate ||
                    this.RuleEndDate != null &&
                    this.RuleEndDate.Equals(other.RuleEndDate)
                ) && 
                (
                    this.RuleId == other.RuleId ||
                    this.RuleId != null &&
                    this.RuleId.Equals(other.RuleId)
                ) && 
                (
                    this.RuleName == other.RuleName ||
                    this.RuleName != null &&
                    this.RuleName.Equals(other.RuleName)
                ) && 
                (
                    this.RuleStartDate == other.RuleStartDate ||
                    this.RuleStartDate != null &&
                    this.RuleStartDate.Equals(other.RuleStartDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Ran != null)
                    hash = hash * 59 + this.Ran.GetHashCode();
                    if (this.Reason != null)
                    hash = hash * 59 + this.Reason.GetHashCode();
                    if (this.RuleEndDate != null)
                    hash = hash * 59 + this.RuleEndDate.GetHashCode();
                    if (this.RuleId != null)
                    hash = hash * 59 + this.RuleId.GetHashCode();
                    if (this.RuleName != null)
                    hash = hash * 59 + this.RuleName.GetHashCode();
                    if (this.RuleStartDate != null)
                    hash = hash * 59 + this.RuleStartDate.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(BreRuleLog left, BreRuleLog right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BreRuleLog left, BreRuleLog right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
