/*
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CartSummary :  IEquatable<CartSummary>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartSummary" /> class.
        /// </summary>
        /// <param name="CreatedDate">The date/time this resource was created in seconds since unix epoch.</param>
        /// <param name="CurrencyCode">The unique id code for the currency used in the cart.</param>
        /// <param name="GrandTotal">The grand total for the cart.</param>
        /// <param name="Id">The unique ID for the cart.</param>
        /// <param name="InvoiceId">The ID of the invoice associated with this cart.</param>
        /// <param name="ItemsInCart">The number of items in the cart.</param>
        /// <param name="Status">The status of the cart.</param>
        /// <param name="Subtotal">The subtotal of all items in the cart.</param>
        public CartSummary(long? CreatedDate = null, string CurrencyCode = null, double? GrandTotal = null, string Id = null, double? InvoiceId = null, int? ItemsInCart = null, string Status = null, double? Subtotal = null)
        {
            this.CreatedDate = CreatedDate;
            this.CurrencyCode = CurrencyCode;
            this.GrandTotal = GrandTotal;
            this.Id = Id;
            this.InvoiceId = InvoiceId;
            this.ItemsInCart = ItemsInCart;
            this.Status = Status;
            this.Subtotal = Subtotal;
            
        }

        /// <summary>
        /// The date/time this resource was created in seconds since unix epoch
        /// </summary>
        /// <value>The date/time this resource was created in seconds since unix epoch</value>
        [DataMember(Name="created_date")]
        public long? CreatedDate { get; set; }

        /// <summary>
        /// The unique id code for the currency used in the cart
        /// </summary>
        /// <value>The unique id code for the currency used in the cart</value>
        [DataMember(Name="currency_code")]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// The grand total for the cart
        /// </summary>
        /// <value>The grand total for the cart</value>
        [DataMember(Name="grand_total")]
        public double? GrandTotal { get; set; }

        /// <summary>
        /// The unique ID for the cart
        /// </summary>
        /// <value>The unique ID for the cart</value>
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// The ID of the invoice associated with this cart
        /// </summary>
        /// <value>The ID of the invoice associated with this cart</value>
        [DataMember(Name="invoice_id")]
        public double? InvoiceId { get; set; }

        /// <summary>
        /// The number of items in the cart
        /// </summary>
        /// <value>The number of items in the cart</value>
        [DataMember(Name="items_in_cart")]
        public int? ItemsInCart { get; set; }

        /// <summary>
        /// The status of the cart
        /// </summary>
        /// <value>The status of the cart</value>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// The subtotal of all items in the cart
        /// </summary>
        /// <value>The subtotal of all items in the cart</value>
        [DataMember(Name="subtotal")]
        public double? Subtotal { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartSummary {\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  CurrencyCode: ").Append(CurrencyCode).Append("\n");
            sb.Append("  GrandTotal: ").Append(GrandTotal).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InvoiceId: ").Append(InvoiceId).Append("\n");
            sb.Append("  ItemsInCart: ").Append(ItemsInCart).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Subtotal: ").Append(Subtotal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((CartSummary)obj);
        }

        /// <summary>
        /// Returns true if CartSummary instances are equal
        /// </summary>
        /// <param name="other">Instance of CartSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartSummary other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.CreatedDate == other.CreatedDate ||
                    this.CreatedDate != null &&
                    this.CreatedDate.Equals(other.CreatedDate)
                ) && 
                (
                    this.CurrencyCode == other.CurrencyCode ||
                    this.CurrencyCode != null &&
                    this.CurrencyCode.Equals(other.CurrencyCode)
                ) && 
                (
                    this.GrandTotal == other.GrandTotal ||
                    this.GrandTotal != null &&
                    this.GrandTotal.Equals(other.GrandTotal)
                ) && 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.InvoiceId == other.InvoiceId ||
                    this.InvoiceId != null &&
                    this.InvoiceId.Equals(other.InvoiceId)
                ) && 
                (
                    this.ItemsInCart == other.ItemsInCart ||
                    this.ItemsInCart != null &&
                    this.ItemsInCart.Equals(other.ItemsInCart)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.Subtotal == other.Subtotal ||
                    this.Subtotal != null &&
                    this.Subtotal.Equals(other.Subtotal)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.CreatedDate != null)
                    hash = hash * 59 + this.CreatedDate.GetHashCode();
                    if (this.CurrencyCode != null)
                    hash = hash * 59 + this.CurrencyCode.GetHashCode();
                    if (this.GrandTotal != null)
                    hash = hash * 59 + this.GrandTotal.GetHashCode();
                    if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                    if (this.InvoiceId != null)
                    hash = hash * 59 + this.InvoiceId.GetHashCode();
                    if (this.ItemsInCart != null)
                    hash = hash * 59 + this.ItemsInCart.GetHashCode();
                    if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                    if (this.Subtotal != null)
                    hash = hash * 59 + this.Subtotal.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(CartSummary left, CartSummary right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CartSummary left, CartSummary right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
