/*
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DeltaResource :  IEquatable<DeltaResource>
    {
                /// <summary>
        /// Whether the question was updated or removed
        /// </summary>
        /// <value>Whether the question was updated or removed</value>
        public enum StateEnum
        {
            
            /// <summary>
            /// Enum UPDATEDEnum for "UPDATED"
            /// </summary>
            [EnumMember(Value = "UPDATED")]
            UPDATEDEnum,
            
            /// <summary>
            /// Enum REMOVEDEnum for "REMOVED"
            /// </summary>
            [EnumMember(Value = "REMOVED")]
            REMOVEDEnum
        }
        /// <summary>
        /// Whether the question was updated or removed
        /// </summary>
        /// <value>Whether the question was updated or removed</value>
        [DataMember(Name="state")]
        public StateEnum? State { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeltaResource" /> class.
        /// </summary>
        /// <param name="CategoryId">The id of the category for question.</param>
        /// <param name="MediaType">The media type of the question.</param>
        /// <param name="QuestionId">The id of the question.</param>
        /// <param name="State">Whether the question was updated or removed.</param>
        /// <param name="Tags">The tags for the question.</param>
        /// <param name="UpdatedDate">The date this question was last updated in seconds since unix epoch.</param>
        public DeltaResource(string CategoryId = default(string), string MediaType = default(string), string QuestionId = default(string), StateEnum? State = default(StateEnum?), List<string> Tags = default(List<string>), long? UpdatedDate = default(long?))
        {
            this.CategoryId = CategoryId;
            this.MediaType = MediaType;
            this.QuestionId = QuestionId;
            this.State = State;
            this.Tags = Tags;
            this.UpdatedDate = UpdatedDate;
            
        }

        /// <summary>
        /// The id of the category for question
        /// </summary>
        /// <value>The id of the category for question</value>
        [DataMember(Name="category_id")]
        public string CategoryId { get; set; }
        /// <summary>
        /// The media type of the question
        /// </summary>
        /// <value>The media type of the question</value>
        [DataMember(Name="media_type")]
        public string MediaType { get; set; }
        /// <summary>
        /// The id of the question
        /// </summary>
        /// <value>The id of the question</value>
        [DataMember(Name="question_id")]
        public string QuestionId { get; set; }
        /// <summary>
        /// The tags for the question
        /// </summary>
        /// <value>The tags for the question</value>
        [DataMember(Name="tags")]
        public List<string> Tags { get; set; }
        /// <summary>
        /// The date this question was last updated in seconds since unix epoch
        /// </summary>
        /// <value>The date this question was last updated in seconds since unix epoch</value>
        [DataMember(Name="updated_date")]
        public long? UpdatedDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeltaResource {\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  MediaType: ").Append(MediaType).Append("\n");
            sb.Append("  QuestionId: ").Append(QuestionId).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  UpdatedDate: ").Append(UpdatedDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((DeltaResource)obj);
        }

        /// <summary>
        /// Returns true if DeltaResource instances are equal
        /// </summary>
        /// <param name="other">Instance of DeltaResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeltaResource other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.CategoryId == other.CategoryId ||
                    this.CategoryId != null &&
                    this.CategoryId.Equals(other.CategoryId)
                ) && 
                (
                    this.MediaType == other.MediaType ||
                    this.MediaType != null &&
                    this.MediaType.Equals(other.MediaType)
                ) && 
                (
                    this.QuestionId == other.QuestionId ||
                    this.QuestionId != null &&
                    this.QuestionId.Equals(other.QuestionId)
                ) && 
                (
                    this.State == other.State ||
                    this.State != null &&
                    this.State.Equals(other.State)
                ) && 
                (
                    this.Tags == other.Tags ||
                    this.Tags != null &&
                    this.Tags.SequenceEqual(other.Tags)
                ) && 
                (
                    this.UpdatedDate == other.UpdatedDate ||
                    this.UpdatedDate != null &&
                    this.UpdatedDate.Equals(other.UpdatedDate)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.CategoryId != null)
                    hash = hash * 59 + this.CategoryId.GetHashCode();
                    if (this.MediaType != null)
                    hash = hash * 59 + this.MediaType.GetHashCode();
                    if (this.QuestionId != null)
                    hash = hash * 59 + this.QuestionId.GetHashCode();
                    if (this.State != null)
                    hash = hash * 59 + this.State.GetHashCode();
                    if (this.Tags != null)
                    hash = hash * 59 + this.Tags.GetHashCode();
                    if (this.UpdatedDate != null)
                    hash = hash * 59 + this.UpdatedDate.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(DeltaResource left, DeltaResource right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DeltaResource left, DeltaResource right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
