/*
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GlobalResource :  IEquatable<GlobalResource>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GlobalResource" /> class.
        /// </summary>
        /// <param name="GlobalDefId">GlobalDefId.</param>
        /// <param name="Scopes">Scopes.</param>
        /// <param name="Type">Type.</param>
        public GlobalResource(string GlobalDefId = default(string), Dictionary<string, ExpressionResource> Scopes = default(Dictionary<string, ExpressionResource>), string Type = default(string))
        {
            this.GlobalDefId = GlobalDefId;
            this.Scopes = Scopes;
            this.Type = Type;
            
        }

        /// <summary>
        /// Gets or Sets GlobalDefId
        /// </summary>
        [DataMember(Name="global_def_id")]
        public string GlobalDefId { get; set; }
        /// <summary>
        /// Gets or Sets Scopes
        /// </summary>
        [DataMember(Name="scopes")]
        public Dictionary<string, ExpressionResource> Scopes { get; set; }
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GlobalResource {\n");
            sb.Append("  GlobalDefId: ").Append(GlobalDefId).Append("\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((GlobalResource)obj);
        }

        /// <summary>
        /// Returns true if GlobalResource instances are equal
        /// </summary>
        /// <param name="other">Instance of GlobalResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GlobalResource other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.GlobalDefId == other.GlobalDefId ||
                    this.GlobalDefId != null &&
                    this.GlobalDefId.Equals(other.GlobalDefId)
                ) && 
                (
                    this.Scopes == other.Scopes ||
                    this.Scopes != null &&
                    this.Scopes.SequenceEqual(other.Scopes)
                ) && 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.GlobalDefId != null)
                    hash = hash * 59 + this.GlobalDefId.GetHashCode();
                    if (this.Scopes != null)
                    hash = hash * 59 + this.Scopes.GetHashCode();
                    if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(GlobalResource left, GlobalResource right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GlobalResource left, GlobalResource right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
