/*
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InvoiceCreateRequest :  IEquatable<InvoiceCreateRequest>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="InvoiceCreateRequest" /> class.
        /// </summary>
        /// <param name="CartGuid">The guid of a cart to create a new invoice for (required).</param>
        public InvoiceCreateRequest(string CartGuid = default(string))
        {
            // to ensure "CartGuid" is required (not null)
            if (CartGuid == null)
            {
                throw new InvalidDataException("CartGuid is a required property for InvoiceCreateRequest and cannot be null");
            }
            else
            {
                this.CartGuid = CartGuid;
            }
            
        }

        /// <summary>
        /// The guid of a cart to create a new invoice for
        /// </summary>
        /// <value>The guid of a cart to create a new invoice for</value>
        [DataMember(Name="cart_guid")]
        public string CartGuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvoiceCreateRequest {\n");
            sb.Append("  CartGuid: ").Append(CartGuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((InvoiceCreateRequest)obj);
        }

        /// <summary>
        /// Returns true if InvoiceCreateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of InvoiceCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvoiceCreateRequest other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.CartGuid == other.CartGuid ||
                    this.CartGuid != null &&
                    this.CartGuid.Equals(other.CartGuid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.CartGuid != null)
                    hash = hash * 59 + this.CartGuid.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(InvoiceCreateRequest left, InvoiceCreateRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InvoiceCreateRequest left, InvoiceCreateRequest right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
