/*
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{

    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PredicateResource :  IEquatable<PredicateResource>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="PredicateResource" /> class.
        /// </summary>
        /// <param name="Args">The arguments the operator apply to. See notes for details. (required).</param>
        /// <param name="Op">The operator to be used in this predicate. See notes for details. (required).</param>
        /// <param name="Type">Type.</param>
        public PredicateResource(List<ExpressionResource> Args = default(List<ExpressionResource>), string Op = default(string), string Type = default(string))
        {
            // to ensure "Args" is required (not null)
            if (Args == null)
            {
                throw new InvalidDataException("Args is a required property for PredicateResource and cannot be null");
            }
            else
            {
                this.Args = Args;
            }
            // to ensure "Op" is required (not null)
            if (Op == null)
            {
                throw new InvalidDataException("Op is a required property for PredicateResource and cannot be null");
            }
            else
            {
                this.Op = Op;
            }
            this.Type = Type;
            
        }

        /// <summary>
        /// The arguments the operator apply to. See notes for details.
        /// </summary>
        /// <value>The arguments the operator apply to. See notes for details.</value>
        [DataMember(Name="args")]
        public List<ExpressionResource> Args { get; set; }
        /// <summary>
        /// The operator to be used in this predicate. See notes for details.
        /// </summary>
        /// <value>The operator to be used in this predicate. See notes for details.</value>
        [DataMember(Name="op")]
        public string Op { get; set; }
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PredicateResource {\n");
            sb.Append("  Args: ").Append(Args).Append("\n");
            sb.Append("  Op: ").Append(Op).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((PredicateResource)obj);
        }

        /// <summary>
        /// Returns true if PredicateResource instances are equal
        /// </summary>
        /// <param name="other">Instance of PredicateResource to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PredicateResource other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Args == other.Args ||
                    this.Args != null &&
                    this.Args.SequenceEqual(other.Args)
                ) && 
                (
                    this.Op == other.Op ||
                    this.Op != null &&
                    this.Op.Equals(other.Op)
                ) && 
                (
                    this.Type == other.Type ||
                    this.Type != null &&
                    this.Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Args != null)
                    hash = hash * 59 + this.Args.GetHashCode();
                    if (this.Op != null)
                    hash = hash * 59 + this.Op.GetHashCode();
                    if (this.Type != null)
                    hash = hash * 59 + this.Type.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(PredicateResource left, PredicateResource right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PredicateResource left, PredicateResource right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
