/*
 * Knetik Platform API Documentation Latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: Latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.SwaggerGen.Annotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class AuthRolesApiController : Controller
    { 

        /// <summary>
        /// Set roles for a client
        /// </summary>
        
        /// <param name="clientKey">The client key</param>
        /// <param name="rolesList">The list of unique roles</param>
        /// <response code="201">Created</response>
        /// <response code="204">No Content</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPut]
        [Route("//auth/clients/{client_key}/roles")]
        [SwaggerOperation("AssignClientRolesUsingPUT")]
        public virtual void AssignClientRolesUsingPUT([FromRoute]string clientKey, [FromBody]List<string> rolesList)
        { 
            throw new NotImplementedException();
        }


        /// <summary>
        /// Set permissions for a role
        /// </summary>
        
        /// <param name="role">The role value</param>
        /// <param name="permissionsList">The list of unique permissions</param>
        /// <response code="201">Created</response>
        /// <response code="204">No Content</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPut]
        [Route("//auth/roles/{role}/permissions")]
        [SwaggerOperation("AssignPermissionsUsingPUT")]
        public virtual void AssignPermissionsUsingPUT([FromRoute]string role, [FromBody]List<string> permissionsList)
        { 
            throw new NotImplementedException();
        }


        /// <summary>
        /// Set roles for a user
        /// </summary>
        
        /// <param name="userId">The user&#39;s id</param>
        /// <param name="rolesList">The list of unique roles</param>
        /// <response code="201">Created</response>
        /// <response code="204">No Content</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPut]
        [Route("//auth/users/{user_id}/roles")]
        [SwaggerOperation("AssignUserRolesExternalUsingPUT")]
        public virtual void AssignUserRolesExternalUsingPUT([FromRoute]int? userId, [FromBody]List<string> rolesList)
        { 
            throw new NotImplementedException();
        }


        /// <summary>
        /// Create a new role
        /// </summary>
        
        /// <param name="roleResource">The role resource object</param>
        /// <response code="201">Created</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPost]
        [Route("//auth/roles")]
        [SwaggerOperation("CreateRoleUsingPOST")]
        [SwaggerResponse(200, type: typeof(RoleResource))]
        public virtual IActionResult CreateRoleUsingPOST([FromBody]RoleResource roleResource)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RoleResource>(exampleJson)
            : default(RoleResource);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Delete a role
        /// </summary>
        
        /// <param name="role">The role value</param>
        /// <param name="force">If true, removes role from users/clients</param>
        /// <response code="204">No Content</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        [HttpDelete]
        [Route("//auth/roles/{role}")]
        [SwaggerOperation("DeleteRoleUsingDELETE")]
        public virtual void DeleteRoleUsingDELETE([FromRoute]string role, [FromQuery]bool? force)
        { 
            throw new NotImplementedException();
        }


        /// <summary>
        /// Get roles for a client
        /// </summary>
        
        /// <param name="clientKey">The client key</param>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("//auth/clients/{client_key}/roles")]
        [SwaggerOperation("GetClientRolesUsingGET")]
        [SwaggerResponse(200, type: typeof(List<RoleResource>))]
        public virtual IActionResult GetClientRolesUsingGET([FromRoute]string clientKey)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<RoleResource>>(exampleJson)
            : default(List<RoleResource>);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Get a single role
        /// </summary>
        
        /// <param name="role">The role value</param>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("//auth/roles/{role}")]
        [SwaggerOperation("GetRoleUsingGET")]
        [SwaggerResponse(200, type: typeof(RoleResource))]
        public virtual IActionResult GetRoleUsingGET([FromRoute]string role)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RoleResource>(exampleJson)
            : default(RoleResource);
            return new ObjectResult(example);
        }


        /// <summary>
        /// List and search roles
        /// </summary>
        
        /// <param name="size">The number of objects returned per page</param>
        /// <param name="page">The number of the page returned, starting with 1</param>
        /// <param name="order">A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC]</param>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("//auth/roles")]
        [SwaggerOperation("GetRolesUsingGET")]
        [SwaggerResponse(200, type: typeof(PageRoleResource))]
        public virtual IActionResult GetRolesUsingGET([FromQuery]int? size, [FromQuery]int? page, [FromQuery]string order)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<PageRoleResource>(exampleJson)
            : default(PageRoleResource);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Get roles for a user
        /// </summary>
        
        /// <param name="userId">The user&#39;s id</param>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("//auth/users/{user_id}/roles")]
        [SwaggerOperation("GetUserRolesUsingGET")]
        [SwaggerResponse(200, type: typeof(List<RoleResource>))]
        public virtual IActionResult GetUserRolesUsingGET([FromRoute]int? userId)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<RoleResource>>(exampleJson)
            : default(List<RoleResource>);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Update a role
        /// </summary>
        
        /// <param name="role">The role value</param>
        /// <param name="roleResource">The role resource object</param>
        /// <response code="201">Created</response>
        /// <response code="204">No Content</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPut]
        [Route("//auth/roles/{role}")]
        [SwaggerOperation("UpdateRoleUsingPUT")]
        public virtual void UpdateRoleUsingPUT([FromRoute]string role, [FromBody]RoleResource roleResource)
        { 
            throw new NotImplementedException();
        }
    }
}
