/*
 * Knetik Platform API Documentation latest 
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://demo.sandbox.knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.SwaggerGen.Annotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class StoreSalesApiController : Controller
    { 

        /// <summary>
        /// Create a sale
        /// </summary>
        
        /// <param name="catalogSale">The catalog sale object</param>
        /// <response code="201">Created</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPost]
        [Route("//store/sales")]
        [SwaggerOperation("CreateCatalogSaleUsingPOST")]
        [SwaggerResponse(200, type: typeof(CatalogSale))]
        public virtual IActionResult CreateCatalogSaleUsingPOST([FromBody]CatalogSale catalogSale)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<CatalogSale>(exampleJson)
            : default(CatalogSale);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Delete a sale
        /// </summary>
        
        /// <param name="id">The id of the sale</param>
        /// <response code="204">No Content</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        [HttpDelete]
        [Route("//store/sales/{id}")]
        [SwaggerOperation("DeleteCatalogSaleUsingDELETE")]
        public virtual void DeleteCatalogSaleUsingDELETE([FromRoute]int? id)
        { 
            throw new NotImplementedException();
        }


        /// <summary>
        /// Get a single sale
        /// </summary>
        
        /// <param name="id">The id of the sale</param>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("//store/sales/{id}")]
        [SwaggerOperation("GetCatalogSaleUsingGET")]
        [SwaggerResponse(200, type: typeof(CatalogSale))]
        public virtual IActionResult GetCatalogSaleUsingGET([FromRoute]int? id)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<CatalogSale>(exampleJson)
            : default(CatalogSale);
            return new ObjectResult(example);
        }


        /// <summary>
        /// List and search sales
        /// </summary>
        
        /// <param name="size">The number of objects returned per page</param>
        /// <param name="page">The number of the page returned, starting with 1</param>
        /// <param name="order">A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC]</param>
        /// <response code="200">OK</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpGet]
        [Route("//store/sales")]
        [SwaggerOperation("GetCatalogSalesUsingGET")]
        [SwaggerResponse(200, type: typeof(PageResourceCatalogSale))]
        public virtual IActionResult GetCatalogSalesUsingGET([FromQuery]int? size, [FromQuery]int? page, [FromQuery]string order)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<PageResourceCatalogSale>(exampleJson)
            : default(PageResourceCatalogSale);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Update a sale
        /// </summary>
        
        /// <param name="id">The id of the sale</param>
        /// <param name="catalogSale">The catalog sale object</param>
        /// <response code="201">Created</response>
        /// <response code="204">No Content</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="403">Forbidden</response>
        /// <response code="404">Not Found</response>
        [HttpPut]
        [Route("//store/sales/{id}")]
        [SwaggerOperation("UpdateCatalogSaleUsingPUT")]
        public virtual void UpdateCatalogSaleUsingPUT([FromRoute]int? id, [FromBody]CatalogSale catalogSale)
        { 
            throw new NotImplementedException();
        }
    }
}
